- NoodleStar/noodlestar-frontend/src/components/NavBar.tsx
- NoodleStar/noodlestar-frontend/src/features/AvailableMenu.css
- NoodleStar/noodlestar-frontend/src/features/AvailableMenuList.tsx
- NoodleStar/noodlestar-frontend/src/pages/MenuOrderPage.tsx
- NoodleStar/noodlestar-frontend/src/path.routes.ts
- NoodleStar/noodlestar-frontend/src/router.tsx
jira link :https://champlainsaintlambert.atlassian.net/browse/NS-32
Implemented the available dishes for orders:
1.  Implemented the available dished page
2.  Implemented the css
3. implemented the routing to the page.
> feat(NS-32):Display Available Dishes for Orders

- NoodleStar/build.gradle
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/BusinessLayer/MenuService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/BusinessLayer/MenuServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/PresentationLayer/MenuController.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/MenuSubdomain/BusinessLayer/MenuServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/MenuSubdomain/PresentationLayer/MenuControllerUnitTest.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/NS-63
AddDish was created without the use of Mono, therefore, this story has a goal of wrapping it in a Mono.
- Made AddDish use Mono in the backend
> feat(NS-63): fix add dish

- NoodleStar/noodlestar-frontend/src/features/Menu.css
- NoodleStar/noodlestar-frontend/src/features/MenuList2.tsx
- NoodleStar/noodlestar-frontend/src/features/api/deleteMenuItem.ts
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/BusinessLayer/MenuService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/BusinessLayer/MenuServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/PresentationLayer/MenuController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/utils/exceptions/DishNameAlreadyExistsException.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/utils/exceptions/InventoryNotFoundException.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/MenuSubdomain/utils/exceptions/NotFoundException.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/MenuSubdomain/BusinessLayer/MenuServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/MenuSubdomain/PresentationLayer/MenuControllerUnitTest.java
**JIRA:** link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/NS-61
Can now delete any menu item.
- Implemented the backend to delete menu by id
- Added the frontend code to display a button that deletes the menu item
- Did the testing to ensure all methods are well
Before:
Button did not exist.
After:
> feat(NS-61): delete menu item

- NoodleStar/build.gradle
- NoodleStar/docker-compose.yml
- NoodleStar/src/main/java/com/noodlestar/noodlestar/GmailSubdomain/EmailController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/GmailSubdomain/GmailService.java
I set up the backend code for the Gmail API
> task(NS-67): set up gmail api

- NoodleStar/noodlestar-frontend/src/components/css/AddReview.css
- NoodleStar/noodlestar-frontend/src/features/Review/AddReview.tsx
- NoodleStar/noodlestar-frontend/src/features/Review/ReviewList.css
- NoodleStar/noodlestar-frontend/src/features/Review/ReviewList.tsx
- NoodleStar/noodlestar-frontend/src/features/UpdateMenu.tsx
- NoodleStar/noodlestar-frontend/src/features/api/Review/addReview.ts
- NoodleStar/noodlestar-frontend/src/path.routes.ts
- NoodleStar/noodlestar-frontend/src/router.tsx
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/BusinessLayer/ReviewService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/BusinessLayer/ReviewServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/PresentationLayer/ReviewController.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/NS-22 
This push is to give customers the ability to leave reviews based on their experience.
- Added the AddReview.tsx with CSS
- Added the backend code for the add review in the ReviewService, ReviewServiceImpl, and ReviewController
- Added routing in Router.tsx and path.route.ts
- Added a button to add a review in the reviews page
Before
After
> feat(NS-43): enable customers to leave reviews

- NoodleStar/noodlestar-frontend/src/components/OrderComponent.tsx
- NoodleStar/noodlestar-frontend/src/features/AvailableMenu.css
- NoodleStar/noodlestar-frontend/src/features/AvailableMenuList.tsx
- NoodleStar/noodlestar-frontend/src/features/api/addDish.ts
- NoodleStar/noodlestar-frontend/src/features/api/createOrder.ts
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderController.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/NS-68 
This ticket is about making the create order work, meaning that it would be created not only on the UI but also in the database.
- Corrected createOrder to create in database
- Fixed order detail's CSS to make it scale alongside the item number
Before: 
After:
> bug(NS-68): fix add item to order

- NoodleStar/noodlestar-frontend/e2e/tests/AddReview.spec.ts
- NoodleStar/noodlestar-frontend/e2e/tests/AddReviewRatingTooHigh.spec.ts
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/PresentationLayer/ReviewController.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ReviewSubdomain/BusinessLayer/ReviewServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ReviewSubdomain/PresentationLayer/ReviewControllerUnitTest.java
This PR is for my backend and E2E tests to add reviews.
- Added my negative and positive testing for add reviews
- Added my two tests for e2e testing
> test: backend and e2e testing for add reviews

- NoodleStar/noodlestar-frontend/e2e/tests/GetOrderSummary.spec.ts
- NoodleStar/noodlestar-frontend/src/features/AvailableMenuList.tsx
- NoodleStar/noodlestar-frontend/src/features/OrderSummary.css
- NoodleStar/noodlestar-frontend/src/features/OrderSummary.tsx
- NoodleStar/noodlestar-frontend/src/features/api/getOrderById.ts
- NoodleStar/noodlestar-frontend/src/pages/OrderSummaryPage.tsx
- NoodleStar/noodlestar-frontend/src/path.routes.ts
- NoodleStar/noodlestar-frontend/src/router.tsx
- NoodleStar/playwright.config.ts
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/businesslayer/OrderService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/businesslayer/OrderServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/datalayer/OrderRepository.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderController.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ordersubdomain/businesslayer/OrderServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderControllerUnitTest.java
- NoodleStar/tests-examples/demo-todo-app.spec.ts
- NoodleStar/tests/example.spec.ts
Reverts Sunveerg/Noodle-Star#28
> feat(NS-24): display order summary

- NoodleStar/noodlestar-frontend/src/components/css/EmailSent.css
- NoodleStar/noodlestar-frontend/src/features/AvailableMenuList.tsx
- NoodleStar/noodlestar-frontend/src/features/EmailSent.tsx
- NoodleStar/noodlestar-frontend/src/features/OrderSummary.tsx
- NoodleStar/noodlestar-frontend/src/features/api/sendEmail.ts
- NoodleStar/noodlestar-frontend/src/pages/EmailSentPage.tsx
- NoodleStar/noodlestar-frontend/src/path.routes.ts
- NoodleStar/noodlestar-frontend/src/router.tsx
- NoodleStar/src/main/java/com/noodlestar/noodlestar/GmailSubdomain/EmailController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/GmailSubdomain/GmailService.java
**JIRA:** https://champlainsaintlambert.atlassian.net/browse/NS-42
This push is to give customers the ability to receive confirmation emails for their order.
- Added EmailSent.tsx with css
- Added sendEmail.ts
- Added routing
Before
Page did exist before
After
Email preview:
> feat(NS-42): set up order confirmation email notifications

- NoodleStar/noodlestar-frontend/src/features/OrderSummary.tsx
- Modified the code to include the email sending function
> bug(NS-78): fix removed code to send email

- NoodleStar/Diagram/SystemSequenceDiagram/Design_Level_SSD(addReview).puml
- NoodleStar/Diagram/SystemSequenceDiagram/penis.puml
- NoodleStar/noodlestar-frontend/src/components/Home.tsx
- NoodleStar/noodlestar-frontend/src/components/css/HomePage.module.css
- NoodleStar/noodlestar-frontend/src/features/Profile.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-15
This ticket is about using auth0 to make sure only users with the staff role have access to the review page through their account
- Added features for Staff profile with button to view reviews
> feat(NS-15): staff profile

- NoodleStar/playwright.config.ts
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/utils/DataSetupServiceReview.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserControllerUnitTest.java
- noodlestar-frontend/e2e/AddStaffRole.spec.ts
- noodlestar-frontend/playwright.config.ts
- noodlestar-frontend/src/features/ManageStaff.tsx
- noodlestar-frontend/src/features/ManageUsers.css
- noodlestar-frontend/src/features/ManageUsers.tsx
- noodlestar-frontend/src/pages/AddStaffPage.tsx
- noodlestar-frontend/src/path.routes.ts
- noodlestar-frontend/src/router.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-81
This ticket is about allowing an owner to add the 'Staff' role to non-staff users.
- Added a page where staff can see the current users
- added a button that allows him to add the staff role to whatever user he wants to
> feat(NS-81): add staff member

- .idea/.gitignore
- .idea/Noodle-Star.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/DataLayer/ReviewRepo.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserRequestModel.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/utils/DataSetupServiceReview.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserControllerUnitTest.java
- noodlestar-frontend/.idea/misc.xml
- noodlestar-frontend/src/Shared/Api/axiosInstance.ts
- noodlestar-frontend/src/components/Home.tsx
- noodlestar-frontend/src/components/css/UpdateStaff.css
- noodlestar-frontend/src/features/ManageStaff.css
- noodlestar-frontend/src/features/ManageStaff.tsx
- noodlestar-frontend/src/features/UpdateStaff.tsx
- noodlestar-frontend/src/features/api/updateStaff.ts
- noodlestar-frontend/src/features/model/userRequestModel.ts
- noodlestar-frontend/src/features/model/userResponseModel.ts
- noodlestar-frontend/src/path.routes.ts
- noodlestar-frontend/src/router.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-82
This PR is to allow owners to modify staff members information, permissions, and roles.
- Added a page where Owners can modify Staff's information
- Fixed duplication issue in the database
- Fixed authentication token issue
> feat(NS-82): update staff info

- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserController.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/PresentationLayer/UserControllerUnitTest.java
- noodlestar-frontend/e2e/UpdateUser.spec.ts
- noodlestar-frontend/src/components/css/HomePage.module.css
- noodlestar-frontend/src/features/Profile.css
- noodlestar-frontend/src/features/Profile.tsx
- noodlestar-frontend/src/features/UpdateUser.tsx
- noodlestar-frontend/src/features/UpdateUserInfo.css
- noodlestar-frontend/src/features/api/updateUser.ts
- noodlestar-frontend/src/pages/UpdateUserPage.tsx
- noodlestar-frontend/src/path.routes.ts
- noodlestar-frontend/src/router.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-48
This PR is to allow users to modify users information
- Added the method update user in the backend
- did all the test in the backend
- implemented the form and the button in the front end
> feat(NS-48): allow users to update account information

- NoodleStar/Diagram/SystemSequenceDiagram/Owner/UpdateStaff.puml
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/businesslayer/OrderService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/businesslayer/OrderServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/datalayer/OrderRepository.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderDetailsRequestModel.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderDetailsResponseModel.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/utils/DataSetupServiceReview.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/utils/EntityDTOUtil.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ordersubdomain/businesslayer/OrderServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ordersubdomain/presentationlayer/OrderControllerUnitTest.java
- noodlestar-frontend/e2e/GetOrderHistory.spec.ts
- noodlestar-frontend/playwright.config.ts
- noodlestar-frontend/src/features/Profile.css
- noodlestar-frontend/src/features/Profile.tsx
- noodlestar-frontend/src/features/api/getOrderByCustomerId.ts
- noodlestar-frontend/src/features/model/orderResponseModel.ts
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-47
This PR is to allow customers to view their order history in their account page
- Added a feature to see order history with customerId decoded from access token
- Added testing both in backend and frontend
> feat(NS-47): display order history for customers

- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/BusinessLayer/ReportService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/BusinessLayer/ReportServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/DataLayer/Report.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/DataLayer/ReportRepository.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/PresentationLayer/ReportController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/PresentationLayer/ReportRequestModel.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReportSubdomain/PresentationLayer/ReportResponseModel.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/utils/DataSetupServiceReview.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ReportSubdomain/BusinessLayer/ReportServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ReportSubdomain/PresentationLayer/ReportControllerUnitTest.java
- noodlestar-frontend/e2e/ViewReport.spec.ts
- noodlestar-frontend/src/features/Profile.css
- noodlestar-frontend/src/features/Profile.tsx
- noodlestar-frontend/src/features/Report.css
- noodlestar-frontend/src/features/ReportList.tsx
- noodlestar-frontend/src/features/api/getAllReports.ts
- noodlestar-frontend/src/features/model/reportRequestModel.ts
- noodlestar-frontend/src/features/model/reportResponseModel.ts
- noodlestar-frontend/src/pages/ReportPage.tsx
- noodlestar-frontend/src/path.routes.ts
- noodlestar-frontend/src/router.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-34
This PR is to allow Owner to see reports about the favorite dishe
- Implemented the report subdomain
- Implement the front end
> feat(NS-34):  Develop a Report to Display Popular Menu Items

- noodlestar-frontend/src/components/Footer.tsx
- noodlestar-frontend/src/components/NavBar.tsx
- noodlestar-frontend/src/components/css/Footer.module.css
- noodlestar-frontend/src/features/Review/ReviewList.tsx
- noodlestar-frontend/src/pages/AboutUsPage.tsx
- noodlestar-frontend/src/pages/AddStaffPage.tsx
- noodlestar-frontend/src/pages/Callbackpage.tsx
- noodlestar-frontend/src/pages/EmailSentPage.tsx
- noodlestar-frontend/src/pages/HomePage.tsx
- noodlestar-frontend/src/pages/ManageStaffPage.tsx
- noodlestar-frontend/src/pages/MenuDetailsPage.tsx
- noodlestar-frontend/src/pages/MenuOrderPage.tsx
- noodlestar-frontend/src/pages/MenuPage.tsx
- noodlestar-frontend/src/pages/OrderSummaryPage.tsx
- noodlestar-frontend/src/pages/ProfilePage.tsx
- noodlestar-frontend/src/pages/ReviewPage.tsx
- noodlestar-frontend/src/pages/UpdateUserPage.tsx
- noodlestar-frontend/src/router.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-51
This PR is to allow users to view the footer component
- Added a footer component to all the pages
- Fixed app not redirecting directly to the home page
> feat(NS-51): add footer

- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/BusinessLayer/ReviewService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/BusinessLayer/ReviewServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/DataLayer/ReviewRepo.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/ReviewSubdomain/PresentationLayer/ReviewController.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceImpl.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ReviewSubdomain/BusinessLayer/ReviewServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/ReviewSubdomain/PresentationLayer/ReviewControllerUnitTest.java
- noodlestar-frontend/e2e/DeleteReview.spec.ts
- noodlestar-frontend/src/features/Review/AllReviewByUserId.tsx
- noodlestar-frontend/src/features/Review/ReviewList.css
- noodlestar-frontend/src/features/Review/ReviewList.tsx
- noodlestar-frontend/src/features/api/deleteReport.ts
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-99
This PR is to allow users to delete reviews
- Implement method in the backend
- Implement the front end
> feat(NS-99): delete review

- noodlestar-frontend/src/features/Callback.tsx
**JIRA:**  https://champlainsaintlambert.atlassian.net/browse/NS-101
This PR is to allow users to Sign up
- Added the sign up functionality
> feat(NS-101): Sign Up

- NoodleStar/docker-compose.yml
- NoodleStar/src/main/java/com/noodlestar/noodlestar/TeamMemberSubdomain/BusinessLayer/TeamMemberService.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/TeamMemberSubdomain/BusinessLayer/TeamMemberServiceImpl.java
- NoodleStar/src/main/java/com/noodlestar/noodlestar/TeamMemberSubdomain/PresentationLayer/TeamMemberController.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/TeamMemberSubdomain/BusinessLayer/TeamMemberServiceUnitTest.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/TeamMemberSubdomain/PresentationLayer/TeamMemberControllerUnitTest.java
- noodlestar-frontend/e2e/deleteTeamMember.ts
- noodlestar-frontend/src/components/AboutUs.tsx
- noodlestar-frontend/src/components/css/AboutUs.module.css
- noodlestar-frontend/src/features/model/teamMemberResponseModel.ts
**JIRA:** link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/NS-97
Owner can now delete team member
- Implemented delete team member method in backend
- Implemented so team members can be deleted by owner in frontend
- Did testing for the method
Before:
There was no button in the card
After:
> feat(NS-97): delete team member

- NoodleStar/src/main/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceImpl.java
- NoodleStar/src/test/java/com/noodlestar/noodlestar/UserSubdomain/BusinessLayer/UserServiceUnitTest.java
- noodlestar-frontend/src/features/Orders.tsx
- noodlestar-frontend/src/features/Profile.tsx
- When customer sign up, he is a customer and not a user
- Orders are displayed is chronological order
- User can collapse order history
> order history

- noodlestar-frontend/src/features/OrderSummary.tsx
> dfhldfhdffd23322
